# fly.toml app configuration file generated for tom-bot-app on 2023-08-11T05:37:09-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tom-bot-app"
primary_region = "yyz"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[processes]
  app = "npm start"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
